declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'
  type Icon = FC<SVGProps<SVGSVGElement> & { size?: number | string; className?: string }>
  export const Activity: Icon
  export const Apple: Icon
  export const ArrowDownLeft: Icon
  export const ArrowLeft: Icon
  export const ArrowRight: Icon
  export const ArrowUpRight: Icon
  export const Bell: Icon
  export const Calendar: Icon
  export const CalendarDays: Icon
  export const Camera: Icon
  export const CameraOff: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const ChevronDown: Icon
  export const ChevronRight: Icon
  export const Chrome: Icon
  export const Clock: Icon
  export const Code: Icon
  export const Coffee: Icon
  export const Coins: Icon
  export const Compass: Icon
  export const Copy: Icon
  export const CreditCard: Icon
  export const Crown: Icon
  export const DollarSign: Icon
  export const Edit2: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const Filter: Icon
  export const Flag: Icon
  export const Flame: Icon
  export const Gamepad2: Icon
  export const Gem: Icon
  export const Gift: Icon
  export const Globe: Icon
  export const Heart: Icon
  export const History: Icon
  export const Home: Icon
  export const Image: Icon
  export const Key: Icon
  export const LayoutPanelTop: Icon
  export const Link2: Icon
  export const Lock: Icon
  export const LogIn: Icon
  export const LogOut: Icon
  export const Mail: Icon
  export const MapPin: Icon
  export const Maximize2: Icon
  export const Menu: Icon
  export const MessageCircle: Icon
  export const Mic: Icon
  export const MicOff: Icon
  export const Monitor: Icon
  export const Moon: Icon
  export const Music: Icon
  export const Palette: Icon
  export const Pause: Icon
  export const Play: Icon
  export const Plus: Icon
  export const Podcast: Icon
  export const Radio: Icon
  export const RefreshCw: Icon
  export const Rocket: Icon
  export const Save: Icon
  export const Search: Icon
  export const Send: Icon
  export const Settings: Icon
  export const Share2: Icon
  export const Shield: Icon
  export const Smartphone: Icon
  export const Smile: Icon
  export const Sparkles: Icon
  export const Star: Icon
  export const Sun: Icon
  export const Tag: Icon
  export const ThumbsUp: Icon
  export const Trash2: Icon
  export const TrendingUp: Icon
  export const Trophy: Icon
  export const User: Icon
  export const UserPlus: Icon
  export const Users: Icon
  export const Video: Icon
  export const Volume2: Icon
  export const VolumeX: Icon
  export const Wallet: Icon
  export const X: Icon
  export const Zap: Icon

  // Fallback for any other icons
  export function createLucideIcon(name: string, content: unknown): Icon
}
